"""Render and validate the inactive nftables policy for isolated CI bridges."""

from __future__ import annotations

import argparse
import ipaddress
import json
import re
import sys
from dataclasses import dataclass
from pathlib import Path
from typing import Any

TABLE_NAME = "python_demo_ci"
_BRIDGE_NAME = re.compile(r"[A-Za-z0-9_.-]{1,15}\Z")
_DOCKER_BRIDGE = re.compile(r"br-[0-9a-f]{12}\Z")
_EXPECTED_FIELDS = {
    "schema_version", "inventory_complete", "trusted_bridges", "protected_bridge_cidrs"
}

_BLOCKED_IPV4 = (
    "0.0.0.0/8",
    "10.0.0.0/8",
    "100.64.0.0/10",
    "127.0.0.0/8",
    "169.254.0.0/16",
    "172.16.0.0/12",
    "192.0.0.0/24",
    "192.0.2.0/24",
    "192.88.99.0/24",
    "192.168.0.0/16",
    "198.18.0.0/15",
    "198.51.100.0/24",
    "203.0.113.0/24",
    "224.0.0.0/4",
    "240.0.0.0/4",
)
_BLOCKED_IPV6 = (
    "::/128",
    "::1/128",
    "::ffff:0:0/96",
    "64:ff9b:1::/48",
    "100::/64",
    "100:0:0:1::/64",
    "2001::/23",
    "2002::/16",
    "2001:db8::/32",
    "3fff::/20",
    "5f00::/16",
    "fc00::/7",
    "fe80::/10",
    "fec0::/10",
    "ff00::/8",
)
_GLOBAL_UNICAST_IPV6 = "2000::/3"


class FirewallPolicyError(ValueError):
    """Raised when a firewall inventory cannot safely produce a policy."""


@dataclass(frozen=True)
class FirewallPolicy:
    trusted_bridges: tuple[str, ...]
    protected_bridge_cidrs: tuple[str, ...]


def _valid_interface(value: Any) -> bool:
    return isinstance(value, str) and bool(_BRIDGE_NAME.fullmatch(value))


def load_policy(data: dict[str, Any]) -> FirewallPolicy:
    """Validate explicit operator inventory before any rules are rendered."""
    if not isinstance(data, dict):
        raise FirewallPolicyError("firewall inventory must be a JSON object")
    unexpected = set(data) - _EXPECTED_FIELDS
    missing = _EXPECTED_FIELDS - set(data)
    if unexpected or missing:
        raise FirewallPolicyError(f"unexpected or missing inventory fields: {sorted(unexpected | missing)}")
    if type(data["schema_version"]) is not int or data["schema_version"] != 1:
        raise FirewallPolicyError("unsupported firewall inventory schema version")
    if data["inventory_complete"] is not True:
        raise FirewallPolicyError("bridge inventory must be marked complete before rendering")

    bridges = data["trusted_bridges"]
    if not isinstance(bridges, list) or not bridges:
        raise FirewallPolicyError("inventory requires at least one explicit trusted bridge exception")
    if any(not _valid_interface(name) for name in bridges):
        raise FirewallPolicyError("trusted bridge entries must be exact interface names without wildcards")
    if "docker0" in bridges:
        raise FirewallPolicyError("docker0 cannot be a trusted bridge exception")
    if len(set(bridges)) != len(bridges):
        raise FirewallPolicyError("trusted bridge inventory contains duplicates")
    cidrs = data["protected_bridge_cidrs"]
    if not isinstance(cidrs, list) or not cidrs:
        raise FirewallPolicyError("inventory requires protected Docker bridge CIDRs")
    if any(not isinstance(value, str) or "/" not in value for value in cidrs):
        raise FirewallPolicyError("protected bridge CIDRs must be explicit strings with a prefix length")
    try:
        normalized_cidrs = tuple(sorted({str(ipaddress.ip_network(value, strict=False)) for value in cidrs}))
    except (TypeError, ValueError) as error:
        raise FirewallPolicyError("protected bridge CIDRs must be valid IPv4 or IPv6 networks") from error
    return FirewallPolicy(tuple(sorted(bridges)), normalized_cidrs)


def _trusted_exceptions(policy: FirewallPolicy, expression: str) -> str:
    return "\n".join(f'        {expression} "{name}" return' for name in policy.trusted_bridges)


def render_policy(policy: FirewallPolicy) -> str:
    """Return a transactional, scoped ruleset; this function never applies it."""
    ipv4_rules = "\n".join(f"        ip daddr {network} drop" for network in _BLOCKED_IPV4)
    ipv6_rules = "\n".join(f"        ip6 daddr {network} drop" for network in _BLOCKED_IPV6)
    bridge_rules = "\n".join(
        f"        {'ip' if ':' not in network else 'ip6'} daddr {network} drop"
        for network in policy.protected_bridge_cidrs
    )
    return f"""# Generated by ci.firewall_policy; review inventory before host installation.
# destroy is scoped to this project-owned table; no ruleset flush is used.
destroy table inet {TABLE_NAME}
destroy table bridge {TABLE_NAME}_l2
table inet {TABLE_NAME} {{
    chain ci_job_egress {{
{ipv4_rules}
{ipv6_rules}
{bridge_rules}
        ip6 daddr != {_GLOBAL_UNICAST_IPV6} drop
        fib daddr type local drop
        udp dport 53 accept
        tcp dport 53 accept
        tcp dport 443 accept
        counter drop
    }}

    chain ci_input {{
        type filter hook input priority -10; policy accept;
{_trusted_exceptions(policy, "iifname")}
        iifname "docker0" counter drop
        iifname "br-*" counter drop
    }}

    chain ci_forward {{
        type filter hook forward priority -10; policy accept;
{_trusted_exceptions(policy, "iifname")}
        iifname "docker0" jump ci_job_egress
        iifname "br-*" jump ci_job_egress
    }}
}}

# Layer-2 guard blocks direct container peers on a CI bridge before IP routing hooks.
table bridge {TABLE_NAME}_l2 {{
    chain ci_bridge_forward {{
        type filter hook forward priority -10; policy accept;
{_trusted_exceptions(policy, "meta ibrname")}
        meta ibrname "docker0" iifname "veth*" oifname "veth*" counter drop
        meta ibrname "br-*" iifname "veth*" oifname "veth*" counter drop
    }}
}}
"""


def validate_bridges(policy: FirewallPolicy, observed_bridges: list[str]) -> None:
    """Fail if the host inventory cannot be covered by the prepared matchers."""
    if not observed_bridges or any(not _valid_interface(name) for name in observed_bridges):
        raise FirewallPolicyError("observed bridge inventory is missing or contains an invalid interface")
    if len(set(observed_bridges)) != len(observed_bridges):
        raise FirewallPolicyError("observed bridge inventory contains duplicate interfaces")
    allowed_custom_names = set(policy.trusted_bridges)
    unsupported = [name for name in observed_bridges if name != "docker0"
                   and not _DOCKER_BRIDGE.fullmatch(name) and name not in allowed_custom_names]
    if unsupported:
        raise FirewallPolicyError(f"unsupported bridge names are outside the default deny matchers: {unsupported}")
    missing = sorted(set(policy.trusted_bridges) - set(observed_bridges))
    if missing:
        raise FirewallPolicyError(f"missing trusted bridge exceptions from the observed host: {missing}")


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--config", required=True, type=Path, help="operator-reviewed bridge inventory JSON")
    parser.add_argument("--bridges", required=True, nargs="+", help="bridge names from a read-only host inventory")
    parser.add_argument("--render", action="store_true", help="print rules only after validation; never applies them")
    arguments = parser.parse_args(argv)
    try:
        policy = load_policy(json.loads(arguments.config.read_text(encoding="utf-8")))
        validate_bridges(policy, arguments.bridges)
    except (OSError, json.JSONDecodeError, FirewallPolicyError) as error:
        print(f"Firewall preflight failed: {error}", file=sys.stderr)
        return 2
    if arguments.render:
        print(render_policy(policy), end="")
    else:
        print("Firewall inventory is valid; no host rules were changed.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
